export const STRAFTATEN = [
  "§ 1.1 StGB – Körperverletzung",
  "§ 1.2 StGB – Mord",
  "§ 1.3 StGB – Totschlag",
  "§ 1.5 StGB – Geiselnahme",
  "§ 1.5a) StGB – Freiheitsberaubung",
  "§ 1.6 StGB – Raub (Laden/ATM/Personen)",
  "§ 1.7 StGB – Wahlbehinderung",
  "§ 1.8 StGB – Vertragsbruch",
  "§ 1.9 StGB – Erpressung",
  "§ 1.9 a) StGB – Betrug",
  "§ 1.10 StGB – Beleidigung",
  "§ 1.10b) StGB – Üble Nachrede",
  "§ 1.11 StGB – Sexuelle Belästigung",
  "§ 1.12 StGB – Dokumentenfälschung",
  "§ 1.13 StGB – Drohung",
  "§ 1.13a) StGB – Gefährliche Drohung",
  "§ 1.14 StGB – Diebstahl",
  "§ 1.14a) StGB – Fahrzeugdiebstahl",
  "§ 1.15 StGB – Nachstellung",
  "§ 1.16) StGB – Unterlassene Hilfeleistung",
  "§ 1.16a) StGB – Behinderung von hilfeleistenden Personen",
  "§ 1.17 StGB – Nötigung",
  "§ 1.18 StGB – Menschenhandel",
  "§ 2.1 StGB – Widerstand gegen Exekutivbeamte",
  "§ 2.1a) StGB – Missachtung behördlicher Anweisungen",
  "§ 2.2 StGB – Sperrzonen-Regelung",
  "§ 2.3 StGB – Behinderung von Ermittlungsverfahren",
  "§ 2.4 StGB – Behinderung von Rettungskräften",
  "§ 2.5 StGB – Fehlverhalten auf staatlichem Organisationsgelände",
  "§ 2.7 StGB – Beihilfe von Gefangenenbefreiung",
  "§ 3.1 StGB – Amtsanmaßung",
  "§ 2.8 StGB – Betreten von Behördenfahrzeugen",
  "§ 3.2 StGB – Tragen einer Vermummung in der Öffentlichkeit",
  "§ 3.3 StGB – Verweigerung der Identitätsfeststellung",
  "§ 3.5 StGB – Illegales Glücksspiel",
  "§ 3.6 StGB – Tragen einer Waffe ohne Waffenschein",
  "§ 3.6a StGB – Waffenmissbrauch",
  "§ 3.7 StGB – Sachbeschädigung",
  "§ 3.8 StGB – Hehlerei und Waffenhandel",
  "§ 3.10 StGB – Hausfriedensbruch",
  "§ 3.12 StGB – Vortäuschen einer Straftat",
  "§ 3.12a) StGB – Androhung der Begehung einer Straftat",
  "§ 3.13 StGB – Meineid",
  "§ 3.14 StGB – Besitz von Behördeneigentum",
  "§ 3.14a) StGB – Missbrauch von Behördeneigentum *",
  "§ 3.14 b) StGB – Medizinische Masken und Medic- / Lifeinvader Westen",
  "§ 3.15 StGB – Besitz von illegalen Waffen",
  "§ 3.16 StGB – Besitz von illegalen Gegenständen",
  "§ 3.17 a) StGB – Kontaktverbot",
  "§ 3.20 StGB – Außergerichtliche Falschaussage",
  "§ 3.21 StGB – Missbrauch eines Notrufes",
  "§ 3.22 StGB – Unterschlagung von Beweismitteln/Straftaten",
  "§ 3.24 StGB – Weitergabe von Lizenzen",
  "§ 3.25 StGB – Privater An- und Verkauf von Arzneimitteln",
  "§ 3.25a) StGB – wiederholter Privater An- und Verkauf von Arzneimitteln",
  "§ 3.26 StGB – ungenehmigte Versammlungen",
  "§ 3.26a) StGB – bewaffnete Versammlungen *",
  "§ 3.27 StGB – Amtsmissbrauch *",
  "§ 3.28 StGB – Umgehen der Meldepflicht von Straftaten",
  "§ 3.29 StGB – Erregung öffentlichen Ärgernisses",
  "§ 3.30 StGB – Tierquälerei",
  "§ 3.31 StGB – Patentrechtsverletzung",
  "§ 3.31a) StGB – Wiederholte Patentrechtsverletzung",
  "§ 3.32 StGB – Sharing-Cars",
  "§ 4.1 StGB – Herstellung von BTM",
  "§ 4.2a) StGB – Besitz von BTM (gering)",
  "§ 4.2b) StGB – Besitz von BTM (hoch)",
  "§ 4.3 StGB – Verkauf/Ankauf von BTM",
  "§ 5.1 StGB – Hochverrat",
  "§ 5.2 StGB – Dienstvergehen",
  "§ 5.3 StGB – Rechtsbelehrung",
  "§ 7.1 StGB – Missbrauch von Lifeinvader Schaltungen",
  "§ 7.1b StGB – Schwerer Missbrauch von Lifeinvader Schaltungen",
  "§ 8.1 StGB – Steuerhinterziehung",
  "§ 8.2 StGB – Schwere Steuerhinterziehung",
  "§ 8.3 StGB – Nicht angezeigte Unternehmensänderung",
  "§ 8.3b StGB – Verstoß trotz Aufforderung",
  "§ 1.3a) StVO – Flucht vor Verkehrskontrolle",
  "§ 1.4 StVO – Stören eines Versorgungstrucks",
  "§ 1.5 StVO – Durchbrechen von Absperrungen",
  "§ 1.6 StVO – Stören eines staatlichen Konvois",
  "§ 2.2 StVO – Fahren ohne Lizenz",
  "§ 2.4 StVO – Belästigung, Behinderung, Gefährdung im Straßenverkehr",
  "§ 2.5 StVO – Einfluss unter BTM",
  "§ 2.8 StVO – Mitführpflicht von Verbandskasten und Reparaturkit",
  "§ 2.9 StVO – Massive Ausnutzung der Hupe",
  "§ 3.5 StVO – Nutzung von High- und Freeway mit Fahrzeugen unter 80 km/h",
  "§ 3.6a) StVO – Geschwindigkeitsüberschreitung 25-100 Km/h",
  "§ 3.6b) StVO – Geschwindigkeitsüberschreitung 101-200 Km/h",
  "§ 3.6c) StVO – Geschwindigkeitsüberschreitung 201-XXX Km/h",
  "§ 4 StVO – Missachtung von entsprechenden Vorfahrtsregelungen",
  "§ 5.5 StVO – Falschparken (Kraftfahrzeuge)",
  "§ 5.6 StVO – Falschparken (Flug Verkehrsmitteln)",
  "§ 6.1 StVO – Fahrzeug mit erheblichen Schäden",
  "§ 6.3 StVO – Fahrzeug mit leerem Tank",
  "§ 8.3 StVO – Fahrerflucht",
  "§ 9 StVO – Nichtbeachtung von Bodenmarkierungen etc.",
  "§ 10 StVO – Gefährlicher Eingriff in den Straßenverkehr",
  "§ 11 StVO – Fahrzeuge ohne Kennzeichen",
  "§ 3 PressG – Einflussnahme auf die Presse",
];
